package com.jacksonasantos.travelplan.dao.interfaces;

public interface ItineraryHasTransportISchema {

    String ITINERARY_HAS_TRANSPORT_TABLE = "itinerary_has_transport";

    String ITINERARY_HAS_TRANSPORT_ID = "id";
    String ITINERARY_HAS_TRANSPORT_TRAVEL_ID = "travel_id";
    String ITINERARY_HAS_TRANSPORT_TRANSPORT_ID = "transport_id";
    String ITINERARY_HAS_TRANSPORT_VEHICLE_ID = "vehicle_id";
    String ITINERARY_HAS_TRANSPORT_ITINERARY_ID ="itinerary_id";
    String ITINERARY_HAS_TRANSPORT_PERSON_ID = "person_id";
    String ITINERARY_HAS_TRANSPORT_TRANSPORT_TYPE = "transport_type";
    String ITINERARY_HAS_TRANSPORT_DRIVER = "driver";
    String ITINERARY_HAS_TRANSPORT_SEQUENCE_ITINERARY = "sequence_itinerary";

    // Version 65
    String CREATE_TABLE_ITINERARY_HAS_TRANSPORT_V65 = "CREATE TABLE IF NOT EXISTS "
            + ITINERARY_HAS_TRANSPORT_TABLE + " ("
            + ITINERARY_HAS_TRANSPORT_ID + " INTEGER PRIMARY KEY, "
            + ITINERARY_HAS_TRANSPORT_TRAVEL_ID + " INTEGER REFERENCES " + TravelISchema.TRAVEL_TABLE + " ("+TravelISchema.TRAVEL_ID+"), "
            + ITINERARY_HAS_TRANSPORT_TRANSPORT_ID + " INTEGER REFERENCES " + TransportISchema.TRANSPORT_TABLE + " ("+TransportISchema.TRANSPORT_ID+"), "
            + ITINERARY_HAS_TRANSPORT_VEHICLE_ID + " INTEGER REFERENCES " + VehicleISchema.VEHICLE_TABLE + " ("+VehicleISchema.VEHICLE_ID+"), "
            + ITINERARY_HAS_TRANSPORT_ITINERARY_ID + " INTEGER REFERENCES " + ItineraryISchema.ITINERARY_TABLE + " ("+ItineraryISchema.ITINERARY_ID+"), "
            + ITINERARY_HAS_TRANSPORT_PERSON_ID + " INTEGER REFERENCES " + PersonISchema.PERSON_TABLE + " ("+PersonISchema.PERSON_ID+"), "
            + ITINERARY_HAS_TRANSPORT_TRANSPORT_TYPE + " INT, "
            + ITINERARY_HAS_TRANSPORT_DRIVER + " INT, "
            +ITINERARY_HAS_TRANSPORT_SEQUENCE_ITINERARY + " INT "
            + ")";

    String[] ITINERARY_HAS_TRANSPORT_COLUMNS = new String[] {
            ITINERARY_HAS_TRANSPORT_ID,
            ITINERARY_HAS_TRANSPORT_TRAVEL_ID,
            ITINERARY_HAS_TRANSPORT_TRANSPORT_ID,
            ITINERARY_HAS_TRANSPORT_VEHICLE_ID,
            ITINERARY_HAS_TRANSPORT_ITINERARY_ID,
            ITINERARY_HAS_TRANSPORT_PERSON_ID,
            ITINERARY_HAS_TRANSPORT_TRANSPORT_TYPE,
            ITINERARY_HAS_TRANSPORT_DRIVER,
            ITINERARY_HAS_TRANSPORT_SEQUENCE_ITINERARY
    };
}
