package com.jacksonasantos.travelplan.dao.interfaces;

public interface MaintenancePlanHasVehicleTypeISchema {

    String MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_TABLE = "maintenance_plan_has_vehicle_type";

    String MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_ID = "id";
    String MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_SERVICE_TYPE = "service_type";
    String MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_MAINTENANCE_PLAN_ID = "maintenance_plan_id";
    String MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_RECURRING_SERVICE = "recurring_service";

    // Version 57
    String CREATE_TABLE_MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_V57 = "CREATE TABLE IF NOT EXISTS "
            + MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_TABLE + " ("
            + MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_ID + " INTEGER PRIMARY KEY, "
            + MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_MAINTENANCE_PLAN_ID + " INTEGER REFERENCES " + MaintenancePlanISchema.MAINTENANCE_PLAN_TABLE + " ("+MaintenancePlanISchema.MAINTENANCE_PLAN_ID+"), "
            + MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_SERVICE_TYPE + " INT, "
            + MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_RECURRING_SERVICE + " INT "
            + ")";

    String[] MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_COLUMNS = new String[] {
             MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_ID,
            MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_MAINTENANCE_PLAN_ID,
             MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_SERVICE_TYPE,
             MAINTENANCE_PLAN_HAS_VEHICLE_TYPE_RECURRING_SERVICE
    };
}
